services:
  nest-chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-chat-nest
    restart: on-failure
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    ports:
      - '3000:3000'

  postgres:
    image: postgres
    container_name: postgres-alpine
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: services
    ports:
      - "5433:5432"
